CREATE PROC FI_SP_IncBeneficiario
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @CPF           VARCHAR (14) ,
    @IDCLIENTE     INT    
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END